#!/usr/bin/env python
import os
import qrencode
import argparse
import rospkg

def host_correct(host):
    try:
        digits = host.split(".")
        assert len(digits) == 4
        for digit in digits:
            digit = int(digit)
            assert 0 <= digit < 256
        return True
    except (ValueError, AssertionError):
        return False

rospack = rospkg.RosPack()
os.chdir(rospack.get_path('robert_beverage') + '/images')

parser = argparse.ArgumentParser(description='generate qr-code')
parser.add_argument('x', metavar='x', type=float, nargs=1)
parser.add_argument('y', metavar='y', type=float, nargs=1)
parser.add_argument('host', metavar='h', type=str, nargs=1)
parser.add_argument('port', metavar='p', type=int, nargs=1)
parser.add_argument('filename', metavar='f', type=str, nargs=1)
args = parser.parse_args()

if not host_correct(args.host[0]):
    raise Exception("host is not correct")

if os.path.isfile(args.filename[0] + '.png'):
    raise Exception("File with exact name already exist")

str_ = "http://{}:{}/beverage?x={}&y={}".format(args.host[0], args.port[0],
                                                args.x[0], args.y[0])
qr = qrencode.encode_scaled(str_, size=100)[2]
qr.save(args.filename[0] + ".png")
print 'Done.'
