#!/usr/bin/env python
import qrencode
import argparse

parser = argparse.ArgumentParser(description='generate qr-code')
parser.add_argument('x-coor', metavar='h', type=str, nargs=1)
parser.add_argument('y-coor', metavar='p', type=str, nargs=1)
parser.add_argument('host', metavar='h', type=str, nargs=1)
parser.add_argument('port', metavar='h', type=str, nargs=1)
parser.add_argument('host', metavar='h', type=str, nargs=1)
x, y, host, port, filename = parser.parse_args().data
str_ = "http://{}:{}/beverage?x={}&y={}".format(host, port, x, y)
qr = qrencode.encode_scaled(str_, size=100)[2]
qr.save(filename + ".png")
print 'Done.'
