#!/usr/bin/env python
import rospy
import python-qrencode

rospy.init_node('generate_qr_code_node')
rospy.loginfo('Inside generate_qr_code script')

while not rospy.is_shutdown():
    x, y, host, port, filename = raw_input("Enter arguments: ").split()
    str_ = "http://{}:{}/beverage?x={}&y={}".format(host, port, x, y)
    qr = python-qrencode.encode(str_)
