#!/usr/bin/env python
import os
import rospy
import socket
import SocketServer
import SimpleHTTPServer
from urlparse import urlparse, parse_qsl
import rospkg

rospy.init_node('web_server_node')
rospy.loginfo('Inside web_server script')
rospack = rospkg.RosPack()

HOST = socket.gethostname()
PORT = 8080
address = ("", PORT)
os.chdir('/')

class RequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path.startswith("/beverage?"):
            parsed = urlparse(self.path)
            params = dict(parse_qsl(parsed.query))
            if len(params) != 2:
                rospy.logerr("Invalid arguments")
            else:
                try:
                    params['x'] = int(params['x'])
                    params['y'] = int(params['y'])
                    rospy.loginfo("x=%d\ty=%d", params['x'], params['y'])
                except ValueError:
                    rospy.logerr("Invalid value")
                except KeyError:
                    rospy.logerr("Invalid arguments")
        else:
            rospy.logerr("Invalid url")
        self.path = rospack.get_path('robert_beverage') + "/scripts/index.html"
        return SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

SocketServer.TCPServer.allow_reuse_address=True
httpd = SocketServer.TCPServer(address, RequestHandler)

rospy.loginfo("serving at port %s", PORT)
httpd.serve_forever()
httpd.shutdown()