#!/usr/bin/env python
import os
import rospy
import socket
import SocketServer
import SimpleHTTPServer
from urlparse import urlparse
import rospkg

rospy.init_node('web_server_node')
rospy.loginfo('Inside web_server script')
rospack = rospkg.RosPack()

HOST = socket.gethostname()
PORT = 8080
address = ("", PORT)
os.chdir('/')

class RequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def do_GET(self):
        try:
            if self.path.startswith("/beverage?"):
                query = urlparse(self.path).query
                coor = dict(qc.split("=")for qc in query.split("&"))
                rospy.loginfo("x=%s\ty=%s", coor['x'], coor['y'])
        except:
            pass
        finally:
            self.path = rospack.get_path('robert_beverage') + "/scripts/index.html"
            rospy.loginfo(self.path)
        return SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

SocketServer.TCPServer.allow_reuse_address=True
httpd = SocketServer.TCPServer(address, RequestHandler)

rospy.loginfo("serving at port %s", PORT)
httpd.serve_forever()
httpd.shutdown()